---
title: "Bicycle infrastructure, Atlanta; August, 2018"
author: "Michael D Garber"
date: "`r Sys.Date()`"
output:
  html_document:
#    toc: true
#    toc_float: true
    number_sections: false
---

Update June 5th, 2023: This is bicycle infrastructure only. Another page has the stratification by roadway type.


# Map of bicycle infrastructure in Atlanta

Bicycle infrastructure in Atlanta within a 5.5-mile radius around Ponce de Leon Ave NE and Monroe Dr NE as of August of 2018.

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(sf)
library(here)
library(mapview)
library(RColorBrewer)
library(leaflet)
library(leaflet.extras) #for popping out full screen
#Note see diss/scripts/aim3-figures.R
setwd(here("data-processed"))
load("edge_mo_infra_study_mo_23_geo.RData")
load("mp_sf_5halfmi.RData")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(RColorBrewer)
library(shades)
greens_6_middle3 = RColorBrewer::brewer.pal(n=6, name  = "Greens")[5:3]  
greens_4 = RColorBrewer::brewer.pal(n=4, name  = "Greens") 
blues_6_top4  = RColorBrewer::brewer.pal(n=6, name  = "Blues")[6:3] 
oranges_6_top4  = RColorBrewer::brewer.pal(n=6, name  = "Oranges")[6:3] 
purples_6_top4  = RColorBrewer::brewer.pal(n=6, name  = "Purples")[6:3] 

infra_custom_pal = c(
  "black",
  brewer.pal(n=3, "Greens")[3],
  brewer.pal(n=3, "Blues")[3],
  brewer.pal(n=3, "Oranges")[3],
  brewer.pal(n=3, "Purples")[3]
)

mv_mp_sf_5halfmi = mp_sf_5halfmi %>% 
  mapview(
    alpha.regions = 0, color = "grey40", col.regions = "grey40",
        layer.name = "Study area")

mv_infra_study_mo_23_infra_custom_pal = edge_mo_infra_study_mo_23_geo %>% 
  #remove some extraneous vars I don't want included in an interactive map
  dplyr::select(
    -starts_with("infra_exclude")) %>% 
  mapview(
    zcol =  "infra_6cat_long_legend_nodirt",  
    color = infra_custom_pal,
    #what about turbo?
#   color=turbo(n=n_distinct(edge_mo_infra_study_mo_23_geo$infra_6cat_long)),
    layer.name = "Infrastructure" ,
    lwd=3,
    alpha=0.9
  )  

mv_infra_custom_pal_both=mv_infra_study_mo_23_infra_custom_pal+ 
  mv_mp_sf_5halfmi
#remove map junk
# mv_infra_custom_pal_both_no_junk=mv_infra_custom_pal_both %>% 
#   mapview::removeMapJunk(
#     junk = c(
#       "layersControl",
#       "zoomControl"
#     ))


#so that it can be popped out full screen
mv_infra_custom_pal_both@map %>% 
  leaflet.extras::addFullscreenControl()
```

