---
title: "Roadway type as classified by OpenStreetMap"
author: "Michael D Garber"
date: "`r Sys.Date()`"
output: html_document
---

Roadway type of roads in Atlanta within a 5.5-mile radius around Ponce de Leon Ave NE and Monroe Dr NE. This excludes interstate highways, service roads, and unclassified roads.
```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(sf)
library(here)
library(mapview)
library(RColorBrewer)
setwd(here("data-processed"))
load("bmap_hwy_for_mapview_aim3.RData") #created in diss/scripts/aim3-figures.R
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
#grouped for a smaller file size
mv_highway_6cat_ordered_with_trunk = bmap_hwy_for_mapview_aim3 %>% 
  mapview(
    layer.name = "Roadway type" ,
    zcol = "highway_6cat_ordered_with_trunk", 
    color = brewer.pal(n=5, name = "Set2"),
    lwd=2, 
    alpha=0.7)   



library(leaflet)
library(leaflet.extras)
#Note I'm not using the usual @map syntax, because the remove junk command
#actually converts it to leaflet
mv_highway_6cat_ordered_with_trunk@map %>% 
  leaflet.extras::addFullscreenControl()

#Note I'm not using the "remove junk" here because the zoom and layers
#could be useful for the web version
```

